{
 "title": "Proofuino",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Bread Temparture",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Box",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sensor",
     "query": "SELECT last(\"bread\") AS \"Current\", mean(\"bread\") AS \"Avg\", max(\"bread\") AS \"Max\", min(\"bread\") AS \"Min\" FROM \"Sensor\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "box" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Box Max" ], "type": "alias" }
      ],
      [
       { "params": [ "box" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "Box Min" ], "type": "alias" }
      ],
      [
       { "params": [ "box" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Box Avg" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Box Temparture",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Box",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sensor",
     "query": "SELECT last(\"box\") AS \"Current\", mean(\"box\") AS \"Avg\", max(\"box\") AS \"Max\", min(\"box\") AS \"Min\" FROM \"Sensor\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "box" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Box Max" ], "type": "alias" }
      ],
      [
       { "params": [ "box" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "Box Min" ], "type": "alias" }
      ],
      [
       { "params": [ "box" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Box Avg" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temparture",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "alias": "Box",
     "measurement": "Sensor",
     "query": "SELECT \"box\" FROM \"Sensor\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "box" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Brot",
     "query": "SELECT mean(\"bread\") FROM \"Sensor\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Power",
     "measurement": "Relais",
     "select": [
      [
       { "params": [ "power" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}