version: '3'
services:
  influxdb:
    image: arm32v7/influxdb:1.8
    container_name: influxdb-container
    volumes:
      - influxdb-data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=proofuino
    ports:
      - "8086:8086"
    network_mode: host
    restart: always

  grafana:
    image: grafana/grafana:main
    container_name: grafana-container
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/dashboard.json:/var/lib/grafana/dashboards/dashboard.json
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    network_mode: host
    restart: always

volumes:
  influxdb-data:
  grafana-data:
