version: '3'
services:
  influxdb:
    image: arm32v7/influxdb:1.8
    container_name: influxdb-container
    volumes:
      - influxdb-data:/var/lib/influxdb
    ports:
      - "8086:8086"
    network_mode: host

  grafana:
    image: grafana/grafana:main
    container_name: grafana-container
    volumes:
      - grafana-data:/var/lib/grafana
      - ./dashboard.json:/var/lib/grafana/dashboards/dashboard.json
    environment:
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/dashboard.json
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    network_mode: host

volumes:
  influxdb-data:
  grafana-data:
