{
 "title": "Proofuino",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Bread Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Box",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sensor",
     "query": "SELECT last(\"bread\") AS \"Current\", median(\"bread\") AS \"Median\", mean(\"bread\") AS \"Avg\", max(\"bread\") AS \"Max\", min(\"bread\") AS \"Min\" FROM \"Sensor\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "box" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Box Max" ], "type": "alias" }
      ],
      [
       { "params": [ "box" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "Box Min" ], "type": "alias" }
      ],
      [
       { "params": [ "box" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Box Avg" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heating Mat",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Box",
     "measurement": "Power",
     "query": "SELECT last(\"bread\") AS \"Current\", mean(\"bread\") AS \"Avg\", max(\"bread\") AS \"Max\", min(\"bread\") AS \"Min\" FROM \"Sensor\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Box Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Box",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sensor",
     "query": "SELECT last(\"box\") AS \"Current\", median(\"box\") AS \"Median\", mean(\"box\") AS \"Avg\", max(\"box\") AS \"Max\", min(\"box\") AS \"Min\" FROM \"Sensor\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "box" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Box Max" ], "type": "alias" }
      ],
      [
       { "params": [ "box" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "Box Min" ], "type": "alias" }
      ],
      [
       { "params": [ "box" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Box Avg" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "alias": "Box",
     "measurement": "Sensor",
     "query": "SELECT \"box\" FROM \"Sensor\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "box" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Brot",
     "measurement": "Sensor",
     "query": "SELECT mean(\"bread\") FROM \"Sensor\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bread" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heating Mat",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "alias": "Box",
     "measurement": "Power",
     "query": "SELECT\n  time,\n  CASE\n    WHEN \"value\" = 1 THEN 'On'\n    WHEN \"value\" = 0 THEN 'Off'\n    ELSE 'Unknown'\n  END AS \"State\"\nFROM \"Power\"\nGROUP BY time, \"State\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Proofuino State",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "alias": "Box",
     "measurement": "State",
     "query": "SELECT last(\"bread\") AS \"Current\", mean(\"bread\") AS \"Avg\", max(\"bread\") AS \"Max\", min(\"bread\") AS \"Min\" FROM \"Sensor\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "state" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}